plugin:
    name: 'beysong.proevent::lang.plugin.name'
    description: 'beysong.proevent::lang.plugin.description'
    author: Beysong
    icon: oc-icon-apple
    homepage: 'http://www.themeshow.cn'
navigation:
    proevent-event-event:
        label: Proevent
        url: beysong/proevent/proevents
        icon: icon-life-ring
        permissions: {  }
