title: Orders
modelClass: Beysong\Proevent\Models\Order
list: $/beysong/proevent/models/order/columns.yaml
recordUrl: 'beysong/proevent/orders/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
