# ===================================
#  Relation Behavior Config
# ===================================

tickets:
    label: Tickets
    view:
        list: $/beysong/proevent/models/ticket/columns.yaml
        toolbarButtons: create|remove
    manage:
        form: $/beysong/proevent/models/ticket/fields.yaml

orders:
    label: Orders
    view:
        list: $/beysong/proevent/models/order/columns.yaml
        toolbarButtons: create|remove
    manage:
        form: $/beysong/proevent/models/order/fields.yaml