title: Events
modelClass: Beysong\Proevent\Models\Event
list: $/beysong/proevent/models/event/columns.yaml
recordUrl: 'beysong/proevent/proevents/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '12'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
